#!/bin/sh
code --install-extension alefragnani.pascal
code --install-extension alefragnani.pascal-formatter
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension fabiospampinato.vscode-diff
code --install-extension formulahendry.code-runner
code --install-extension icrawl.discord-vscode
code --install-extension kosz78.nim
code --install-extension krvajalm.linter-gfortran
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.python
code --install-extension ms-vscode.cmake-tools
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.Go
code --install-extension ow.vscode-subword-navigation
code --install-extension Perkovec.emoji
code --install-extension siegebell.incremental-search
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension streetsidesoftware.code-spell-checker-russian
code --install-extension twxs.cmake
code --install-extension Tyriar.sort-lines
code --install-extension vscode-icons-team.vscode-icons
code --install-extension vscodevim.vim
code --install-extension zhuangtongfa.material-theme
