#!/bin/sh
code \
--install-extension alefragnani.pascal \
--install-extension alefragnani.pascal-formatter \
--install-extension eamodio.gitlens \
--install-extension EditorConfig.EditorConfig \
--install-extension fabiospampinato.vscode-diff \
--install-extension formulahendry.code-runner \
--install-extension icrawl.discord-vscode \
--install-extension kosz78.nim \
--install-extension krvajalm.linter-gfortran \
--install-extension ms-azuretools.vscode-docker \
--install-extension ms-python.python \
--install-extension ms-vscode.cmake-tools \
--install-extension ms-vscode.cpptools \
--install-extension ms-vscode.Go \
--install-extension ow.vscode-subword-navigation \
--install-extension Perkovec.emoji \
--install-extension siegebell.incremental-search \
--install-extension streetsidesoftware.code-spell-checker \
--install-extension streetsidesoftware.code-spell-checker-russian \
--install-extension twxs.cmake \
--install-extension Tyriar.sort-lines \
--install-extension vscode-icons-team.vscode-icons \
--install-extension vscodevim.vim \
